post 'approvers/approv', :to => 'approvers#approv', :as => 'approv'
delete 'approvers/approv', :to => 'approvers#unapprov'
get 'approvers/new', :to => 'approvers#new'
post 'approvers', :to => 'approvers#create'
post 'approvers/append', :to => 'approvers#append'
delete 'approvers', :to => 'approvers#destroy'
get 'approvers/autocomplete_for_user', :to => 'approvers#autocomplete_for_user'
# Specific routes for issue approvers API
post 'issues/:object_id/approvers', :to => 'approvers#create', :object_type => 'issue'
delete 'issues/:object_id/approvers/:user_id' => 'approvers#destroy', :object_type => 'issue'
