post 'approvers/approve', to: 'approvers#approve', as: 'approve'
delete 'approvers/approve', to: 'approvers#unapprove'
get 'approvers/new', to: 'approvers#new'
post 'approvers', to: 'approvers#create'
post 'approvers/append', to: 'approvers#append'
delete 'approvers', to: 'approvers#destroy'
post 'approvers/do_approve', to: 'approvers#do_approve', as: 'do_approve'
delete 'approvers/do_approve', to: 'approvers#undo_approve'
get 'approvers/autocomplete_for_user', to: 'approvers#autocomplete_for_user'
# Specific routes for issue approvers API
post 'issues/:object_id/approvers', to: 'approvers#create', object_type: 'issue'
delete 'issues/:object_id/approvers/:user_id' => 'approvers#destroy', object_type: 'issue'
